stages:
  - build
  - unitTests
  # Use only if the marking-svc-tests-env is not available
  - createMarkingSvcTestEnvironment
  # The Gitlab CI pipeline is very slow for running these tests. Better run them locally
  - integrationTests
  - deploy

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_REGISTRY: "nexus.informatik.haw-hamburg.de"
  SERVICE_NAME: "marking-svc"

cache:
  untracked: true

build:
  stage: build
  image: ${DOCKER_REGISTRY}/microsoft/dotnet:2.0.0-sdk
  tags:
    - k8s
  script:
    - dotnet clean -c Release -v minimal /maxcpucount
    - dotnet build -c Release -v minimal /maxcpucount
    - dotnet publish -o ./out -v minimal /maxcpucount
  artifacts:
    untracked: true

unitTests:
  stage: unitTests
  image: ${DOCKER_REGISTRY}/microsoft/dotnet:2.0.0-sdk
  tags:
    - k8s
  script:
   - cd UnitTests
   - dotnet test -c Release -v minimal /maxcpucount

createMarkingSvcTestEnvironment:
  when: manual
  stage: createMarkingSvcTestEnvironment
  image: ${DOCKER_REGISTRY}/docker:stable-dind
  tags:
    - k8s
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - cd MarkingSvcTestEnvironment
    - sh ./start.sh

integrationTests:
  when: manual
  stage: integrationTests
  image: ${DOCKER_REGISTRY}/marking-svc-test-env
  tags:
    - k8s
  script:
   - cd IntegrationTests
   - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
   - docker-compose run marking-svc-tests /maxcpucount

deploy:
  stage: deploy
  image: ${DOCKER_REGISTRY}/docker:stable-dind
  tags:
    - k8s
  only:
    - master
  script:
    - docker login -u $NEXUS_USER -p $NEXUS_PW $DOCKER_REGISTRY
    - docker build -t $SERVICE_NAME:latest .
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID
    - docker tag $SERVICE_NAME:latest $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHA
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:latest
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_PIPELINE_ID    
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHA