version: '3'

services:
  mongo-seed:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    volumes:
      - ./seed-data:/seed-data
    entrypoint:
      - sh
    command:
      - ./seed-data/seed-data.sh
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    expose:
      - 27017

  metadata-svc:
    image: nexus.informatik.haw-hamburg.de/metadata-svc:22434
    environment:
      - METADATA_SVC_URL=metadata-svc:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    expose:
      - 8080

  marking-svc-tests:
    image: nexus.informatik.haw-hamburg.de/microsoft/dotnet:2.0.0-sdk
    volumes:
      - ../:/mars-marking-svc
    entrypoint:
      - sh
    command:
      - ./mars-marking-svc/IntegrationTests/run_tests.sh
    links:
      - mongodb
      - metadata-svc
    depends_on:
      - mongodb
      - metadata-svc