version: '3'

services:
  mongodb:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    ports:
      - "27017:27017"
    
  mongo-seed:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    links:
      - mongodb
    volumes:
      - ./seed-data:/seed-data
    command:
      # metadata-svc
      - "mongoimport --host mongodb --port 27017 --db import --collection metadata --type json --file /seed-data/people.json --jsonArray"
      
