version: '3'

services:
  mongo-seed:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    volumes:
      - ./_SeedData:/SeedData
    entrypoint:
      - sh
    command:
      - ./SeedData/seed_data.sh
    links:
      - mongodb
    depends_on:
      - mongodb
      
  result-mongo-seed:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    volumes:
      - ./_SeedResultData:/SeedResultData
    entrypoint:
      - sh
    command:
      - ./SeedResultData/seed_data.sh
    links:
      - result-mongodb
    depends_on:
      - result-mongodb

  mongodb:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    expose:
      - 27017

  result-mongodb:
    image: nexus.informatik.haw-hamburg.de/mongo:3.4.1
    expose:
      - 27017
        
  project-postgres:
    image: nexus.informatik.haw-hamburg.de/postgres:9.6-alpine
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=projectsvc
      - POSTGRES_PASSWORD=mariokart102
    expose:
      - 5432
      
  project-svc:
    # TODO: Change image tag once merged
    image: nexus.informatik.haw-hamburg.de/project-svc:dev
    environment:
      - POSTGRES_DB=project
      - POSTGRES_USER=projectsvc
      - POSTGRES_PASSWORD=mariokart102
    links:
      - project-postgres
    depends_on:
      - project-postgres
    expose:
      - 80

  metadata-svc:
    image: nexus.informatik.haw-hamburg.de/metadata-svc:latest
    links:
      - mongodb
    depends_on:
      - mongodb
    expose:
      - 8080
  
  scenario-svc:
    # TODO: Change image tag once merged
    image: nexus.informatik.haw-hamburg.de/scenario-svc:dev
    links:
      - mongodb
    depends_on:
      - mongodb
    expose:
      - 8080
      
  resultcfg-svc:
    image: nexus.informatik.haw-hamburg.de/resultcfg-svc:latest
    links:
      - mongodb
    depends_on:
      - mongodb
    expose:
      - 8080
      
  sim-runner-svc:
    image: nexus.informatik.haw-hamburg.de/sim-runner-svc:latest
    links:
      - mongodb
    depends_on:
      - mongodb
    expose:
      - 8080
      
  database-utility-svc:
    # TODO: Change image tag once merged
    image: nexus.informatik.haw-hamburg.de/database-utility-service:dev
    links:
      - result-mongodb
    depends_on:
      - result-mongodb
    expose:
      - 8090

  marking-svc-tests:
    image: nexus.informatik.haw-hamburg.de/microsoft/dotnet:2.0.0-sdk
    environment:
      - PROJECT_SVC_URL=project-svc:80
      - METADATA_SVC_URL=metadata-svc:8080
      - SCENARIO_SVC_URL=scenario-svc:8080
      - RESULT_CONFIG_SVC_URL=resultcfg-svc:8080
      - SIM_RUNNER_SVC_URL=sim-runner-svc:8080
      - DATABASE_UTILITY_SVC_URL=database-utility-svc:8090
      - MONGO_DB_SVC_URL=mongodb://mongodb:27017
    volumes:
      - ../:/mars-marking-svc
    entrypoint:
      - sh
    command:
      - ./mars-marking-svc/IntegrationTests/docker_tests_entrypoint.sh
    links:
      - mongodb
      - project-svc
      - metadata-svc
      - scenario-svc
      - resultcfg-svc
      - sim-runner-svc
      - database-utility-svc
    depends_on:
      - mongo-seed
      - result-mongo-seed
      - mongodb
      - result-mongodb
      - project-postgres
      - project-svc
      - metadata-svc
      - scenario-svc
      - resultcfg-svc
      - sim-runner-svc
      - database-utility-svc